export const enum REQ_PATHS {
	CONVERT_VIDEO_TO_AUDIO = "/video/convert_to_audio",
	CONVERT_VIDEO_TO_OTHER_FORMAT = "/video/convert_to_other_format",
	VIDEO_CONVERT_MKV_TO_MP4 = "/video/mkv_to_mp4",
	COMBINE_VIDEO_AND_AUDIO = "/video/combine_audio",
	TRIM_VIDEO = "/video/trim",
	CROP_VIDEO = "/video/crop",
	QUERY_VIDEO_INFO = "/video/info",
	COMBINE_VIDEOS = "/video/combine",
	SPEED_UP_VIDEO = "/video/speed_up",
	COMBINE_VIDEO_SUBTITLE = "/video/combine_subtitle",
	QUERY_AUDIO_INFO = "/audio/info",
	CONVERT_AUDIO_TO_OTHER_FORMAT = "/audio/convert_to_other_format",
	REMOVE_AUDIO_FROM_VIDEO = "/video/remove_audio",
	QUERY_AUDIO_SQUARE_REARCH = "/audio/square_search",
	SILENT_PARTIAL_AUDIO = "/audio/silent_parial",
	CROP_AUDIO = "/audio/crop",
}
